### ISSUE TITLE
OS 팀원분들을 구합니다.

### ISSUE THREAD

**Issue by hyeongyukim** [swsnu/osspr2022#20]
안녕하세요, 전기정보공학부 17학번 김현규입니다.
조금 늦은 것 같기는 하지만 그래도 팀원을 구해보고자 글을 올립니다.

clang에 기여해본 적이있고 그 과정에서 발견한 취약점을 리눅스 커널에 제보해본 경험이 있어 C프로그래밍자체는 익숙한 편입니다.
OS를 드랍하면 한 학기를 더 다녀야 되다보니 드랍은 절대 하지 않을 예정입니다!!

그래서... 힘들어도 한 학기동안 드랍하지 않고 잘 버텨보실 팀원 두 분 구합니다!!
저처럼 아직 한 명도 구하지 못한 분도 괜찮고 마지막 한 명을 찾고 계신 분들도 좋습니다 :)

**Comment by hyeongyukim** [comment]
한분은 구했습니다. 혹시 팀원을 구하시지 못한 분이 계시면 연락주세요.

**Comment by sstto** [comment]
안녕하세요. 지구환경과학부 16학번 심영인입니다. 팀원 희망합니다
