### ISSUE TITLE
OS 팀플 같이 하실 분 구합니다.

### ISSUE THREAD

**Issue by cw10108** [swsnu/osspr2022#3]
안녕하세요, 한 학기 동안 OS 팀플 같이 하실 분 구합니다.
지금 저 포함 2명이고, 한 분만 더 오시면 됩니다.

저희 둘은 방학 때 같은 팀 인턴으로 웹 개발 관련 협업을 한 번 했었고, 그 때 합이 잘 맞아서 이번 팀플도 같이 하게 되었습니다.
때문에 협업이나 지뢰(ㅎㅎ)관련해서는 문제가 없으리라 예상합니다.

둘 다 졸업 학기라 학점 수도 많지 않아 시간도 잘 쓸 수 있으리라 예상합니다.
같이 하실 분 모집합니다!

**Comment by cw10108** [comment]
@GoGiants1

**Comment by hannafoe** [comment]
안녕하세요. 혹시 아직 팀원 정하지 안핬다면 제가 같이 해도 될까요?

**Comment by hannafoe** [comment]
저는 지금 3학년 2학기이고 교환학생이기 때문에 그렇게 많은 수업을 듣지 않았기 때문에 이 수업에는 많은 시간을 쓸 수 있습니다. 제 한국어는 아직 부적당한 부분도 있겠지만 프로그래밍은 잘 할 수 있겠다고 생각합니다. C에서는 프로그래밍을 많이 해왔습니다. 안돼면 다른 팀을 찾아야하니까 답장을 보내줬으면 좋겠습니다. 감사합니다!!

**Comment by GoGiants1** [comment]
안녕하세요. 먼저 연락주셔서 감사합니다. 이런 경우는 처음이긴한데, 같이 팀을 이루기는 힘들 것 같습니다. 죄송합니다 ㅠㅠ
