### ISSUE TITLE
OS 팀플 같이 하실 분 구합니다!

### ISSUE THREAD

**Issue by juimdpp** [swsnu/osspr2022#4]
안녕하세요, 컴퓨터공학부 18학번 김현수입니다.

독강이어서 팀원 두분 구합니다!

이번 학기에는 OS 포함 10~13학점 수강할 예정입니다. 시스템에 관심이 많아 드랍할 가능성 없습니다.
시스템 프로그래밍 수업을 힘들지만 열심히 들었어서 OS도 비슷하게, 힘들어도 열심히 들을 계획입니다!
같이 함께할 두분 구합니다 :) 

감사합니다.

**Comment by jungi-lee** [comment]
@juimdpp 메일 보냈는데 확인 부탁드려도 될까요?
