### ISSUE TITLE
[proj3] sched_getweight 시스템콜 스펙 변경 관련 질문

### ISSUE THREAD

**Issue by iks15174** [swsnu/osspr2022#98]
안녕하세요.
`sched_getweight` 시스템콜 스펙 변경 관련해서 여쭤볼 것이 있어 질문 올립니다.
- `pid: target task's PID. PID 0 indicates the calling task.` -> `pid: target task's PID.` 변경이 되었는데, 이러면 PID에 0을 넣어서 `sched_getweight` 을 호출할 경우 PID가 0인 프로세스의 weight를 return 해주는게 맞나요??
- 그리고 `sched_setweight` 은 그대로이고 `sched_getweight` 만 바뀌는 게 맞나요??
감사합니다.

**Comment by t-hyun** [comment]
안녕하세요. 공지 없는 스펙 변경은 하지 않고 위의 변화는 실수입니다. 빠르게 알려주셔서 감사합니다. 혹시 issue를 지워주실 수 있으신가요? 죄송합니다.

**Comment by iks15174** [comment]
네 알겠습니다!
